### ISSUE TITLE
phpMyAdmin SQL Dump causing issues with SQL file in SQL Server Studio Management Studio

### ISSUE THREAD

**Issue by trevor-schmidt1214** [hanlinag/point-of-sale-system#1]
Incorrect Syntax near errors. possibly an encoding issue. Could you possibly validate your .sql file is correct in SSMS?

![image](https://user-images.githubusercontent.com/22626064/112041907-4998df80-8b1d-11eb-8961-e836597ab3d9.png)

**Comment by trevor-schmidt1214** [comment]
Worked through the sql query. int requires no () or value. also the ENGINE=InnoDB DEFAULT CHARSET=utf8; code was not working. I had to remove all ` marks and transaction needed to be around "s. I also removed all comments and removed the SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

**Comment by hanlinag** [comment]
Thanks for the issue. If it's working now, I will close the issue. :)
