### ISSUE TITLE
I can't run the project

### ISSUE THREAD

**Issue by phyoheinkyaw** [hanlinag/point-of-sale-system#3]
It's always say
"Error: Unable to initialize main class major.Login
Caused by: java.lang.NoClassDefFoundError: Stage"

**Comment by hanlinag** [comment]
That is the common error when you import projects to your Eclipse workspace. Please refer the following issue: 
https://stackoverflow.com/questions/16868446/javafx-exception-in-thread-main-java-lang-noclassdeffounderror-javafx-applica

As this is not the issue from project directly, I will close the issue now. :)
